-- Insert Categories
INSERT INTO categories (name)
VALUES ('Fruits'),
       ('Vegetables'),
       ('Dairy'),
       ('Bakery'),
       ('Beverages'),
       ('Snacks'),
       ('Frozen Foods'),
       ('Meat'),
       ('Seafood'),
       ('Household');

-- Insert Products
INSERT INTO products (name, price, description, category_id)
VALUES ('Bananas 1kg',
        5.99,
        'Fresh premium bananas sourced from Ecuador. Rich in potassium and perfect for smoothies or snacks.',
        1),
       ('Organic Tomatoes 500g',
        7.50,
        'Locally grown organic tomatoes with a juicy texture and rich flavor, ideal for salads and cooking.',
        2),
       ('Almarai Full Fat Milk 1L',
        6.25,
        'Fresh full fat milk packed with calcium and essential nutrients for everyday nutrition.',
        3),
       ('Whole Wheat Bread',
        4.75,
        'Soft and healthy whole wheat bread baked daily with high fiber content.',
        4),
       ('Coca-Cola 330ml Can',
        2.50,
        'Classic refreshing carbonated soft drink served chilled for the best taste.',
        5),
       ('Lays Classic Chips 170g',
        8.99,
        'Crispy salted potato chips made from farm-grown potatoes for a classic snack experience.',
        6),
       ('Americana Chicken Nuggets 750g',
        18.95,
        'Frozen chicken nuggets made with tender chicken breast meat, quick and easy to prepare.',
        7),
       ('Australian Beef Mince 500g',
        24.50,
        'Premium quality halal Australian beef mince suitable for burgers, pasta, and curries.',
        8),
       ('Fresh Atlantic Salmon Fillet 300g',
        39.99,
        'Fresh Atlantic salmon fillet rich in omega-3 fatty acids and ideal for grilling or baking.',
        9),
       ('Dettol Antibacterial Surface Cleaner 500ml',
        12.75,
        'Powerful antibacterial cleaner that removes germs and leaves surfaces hygienically clean.',
        10);